### ISSUE TITLE
proxyConsole.js:56 Warning: Unknown props `onTypingEnd`, `initDelay`, `typing`, `maxDelay`, `minDelay` on <span> tag.

### ISSUE THREAD

**Issue by drakejin** [ianbjorndilling/react-typewriter#29]
### Version
0.4.1

### Steps to reproduce
1. jsx source code : 

```  jsx
                    <TypeWriter
                      onTypingEnd={this.typeIsDone.bind(this)}
                      initDelay={2000}
                      typing={this.state.erase}>
                      {this.state.messages[this.state.index]}
                    </TypeWriter>
```

2. component  same as source 1
```
  constructor(props) {
    super(props);

    this.state={
      messages:["선배와 동기의 A+ 비결", "선배, 친구", "과제, 족보", "썸녀의 썸남저격", "썸남의 썸녀저격"],
      index:0,
      erase:1
    }
  }
  typeIsDone(){
    if(this.state.erase == -1){
      if(this.state.index+1 >=  this.state.messages.length){
        this.setState({
          erase:1,
          index:0
        })
      }else{
        this.setState({
          erase:1,
          index:this.state.index+1
        });
      }
    }else{
      this.setState({
        erase:-1
      })
    }
  }
```

3. shit.

proxyConsole.js:56 Warning: Unknown props `onTypingEnd`, `initDelay`, `typing`, `maxDelay`, `minDelay` on <span> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop

### Expected behavior
loop messages

### Actual behavior
le.js:56 Warning: Unknown props `onTypingEnd`, `initDelay`, `typing`, `maxDelay`, `minDelay` on <span> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop

**Comment by archae0pteryx** [comment]
same error here

**Comment by matmac** [comment]
Any solution to this issue? I'm experiencing the same problem.

Warning: Unknown props onTypingEnd, initDelay, typing, maxDelay, minDelay on tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop

Also the typewritter stops working, cannot reverse or delete the text.

**Comment by dbrrt** [comment]
+1

**Comment by RoosDaniel** [comment]
Still experiencing this.

**Comment by drakejin** [comment]
I think this repo is over and deprecated, I'll quit
